[package]
name = "testrudder"
version = "1.0.0"
edition = "2018"
readme = "README.md"


[[bin]]
name = "rudder"
path = "src/main.rs"
required-features = ["cli"]

[dependencies]
failure = "0.1.5"
reqwest = "0.9"
serde_json = "1.0.39"
log = "0.4.14"

[dependencies.chrono]
features = ["serde"]
version = "0.4.6"

[dependencies.clap]
optional = true
version = "2.33"

[dependencies.serde]
features = ["derive"]
version = "1.0.93"

[features]
cli = ["clap"]
